In [1]:
import numpy as np

# Задание 1

In [2]:
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

identity_matrix = np.eye(3)

In [3]:
result_matrix = matrix_a + identity_matrix

In [4]:
vector = np.array([1, 2, 3])
product_result = np.dot(result_matrix, vector)

In [5]:
transposed_matrix = result_matrix.T

In [6]:
#Считаю обратную матрицу к полученной в результате прибавления матрице
inverse_matrix = np.linalg.inv(result_matrix)

In [7]:
print("Исходная матрица (1-9):\n", matrix_a)
print("\nМатрица с единицами на диагонали:\n", identity_matrix)
print("\nРезультирующая матрица после прибавления:\n", result_matrix)
print("\nРезультат умножения на вектор (1, 2, 3):\n", product_result)
print("\nТранспонированная матрица:\n", transposed_matrix)
print("\nОбратная матрица:\n", inverse_matrix)

Исходная матрица (1-9):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Матрица с единицами на диагонали:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Результирующая матрица после прибавления:
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]

Результат умножения на вектор (1, 2, 3):
 [15. 34. 53.]

Транспонированная матрица:
 [[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]]

Обратная матрица:
 [[-6.  -2.   3. ]
 [-1.   0.5  0. ]
 [ 5.   1.  -2. ]]


# Задние 2

In [8]:
m = np.array([[2, 2],
              [1, 3]])

In [9]:
eigenvalues, eigenvectors = np.linalg.eig(m)

In [10]:
print("Матрица:\n", m)
print("\nСобственные значения:\n", eigenvalues)
print("\nСобственные векторы:\n", eigenvectors)

Матрица:
 [[2 2]
 [1 3]]

Собственные значения:
 [1. 4.]

Собственные векторы:
 [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


# Задание 3

In [11]:
matrix = np.array([[1, 1],
                   [1, 2]])

In [12]:
determinant = np.linalg.det(matrix)

In [13]:
print("Матрица:\n", matrix)
print("\nОпределитель матрицы:", determinant)

Матрица:
 [[1 1]
 [1 2]]

Определитель матрицы: 1.0
